import TwoTouchParser
import Testing

actor TwoTouchDecoderTests {
  @Test
  func decode_1112324493() throws {
    let decoder = TwoTouchDecoder()
    let result = try! decoder.decode(from: "1112324493")
    #expect(result == "アイシテル")
  }
  
  @Test
  func decode() throws {
    let decoder = TwoTouchDecoder()
    #expect(try decoder.decode(from: "00") == "0")
    #expect(try decoder.decode(from: "01") == "ワ")
    #expect(try decoder.decode(from: "02") == "ヲ")
    #expect(try decoder.decode(from: "03") == "ン")
    #expect(try decoder.decode(from: "04") == "゛")
    #expect(try decoder.decode(from: "05") == "。")
    #expect(try decoder.decode(from: "06") == "6")
    #expect(try decoder.decode(from: "07") == "7")
    #expect(try decoder.decode(from: "08") == "8")
    #expect(try decoder.decode(from: "09") == "9")
    #expect(try decoder.decode(from: "10") == "E")
    #expect(try decoder.decode(from: "11") == "ア")
    #expect(try decoder.decode(from: "12") == "イ")
    #expect(try decoder.decode(from: "13") == "ウ")
    #expect(try decoder.decode(from: "14") == "エ")
    #expect(try decoder.decode(from: "15") == "オ")
    #expect(try decoder.decode(from: "16") == "A")
    #expect(try decoder.decode(from: "17") == "B")
    #expect(try decoder.decode(from: "18") == "C")
    #expect(try decoder.decode(from: "19") == "D")
    #expect(try decoder.decode(from: "20") == "J")
    #expect(try decoder.decode(from: "21") == "カ")
    #expect(try decoder.decode(from: "22") == "キ")
    #expect(try decoder.decode(from: "23") == "ク")
    #expect(try decoder.decode(from: "24") == "ケ")
    #expect(try decoder.decode(from: "25") == "コ")
    #expect(try decoder.decode(from: "26") == "F")
    #expect(try decoder.decode(from: "27") == "G")
    #expect(try decoder.decode(from: "28") == "H")
    #expect(try decoder.decode(from: "29") == "I")
    #expect(try decoder.decode(from: "30") == "O")
    #expect(try decoder.decode(from: "31") == "サ")
    #expect(try decoder.decode(from: "32") == "シ")
    #expect(try decoder.decode(from: "33") == "ス")
    #expect(try decoder.decode(from: "34") == "セ")
    #expect(try decoder.decode(from: "35") == "ソ")
    #expect(try decoder.decode(from: "36") == "K")
    #expect(try decoder.decode(from: "37") == "L")
    #expect(try decoder.decode(from: "38") == "M")
    #expect(try decoder.decode(from: "39") == "N")
    #expect(try decoder.decode(from: "40") == "T")
    #expect(try decoder.decode(from: "41") == "タ")
    #expect(try decoder.decode(from: "42") == "チ")
    #expect(try decoder.decode(from: "43") == "ツ")
    #expect(try decoder.decode(from: "44") == "テ")
    #expect(try decoder.decode(from: "45") == "ト")
    #expect(try decoder.decode(from: "46") == "P")
    #expect(try decoder.decode(from: "47") == "Q")
    #expect(try decoder.decode(from: "48") == "R")
    #expect(try decoder.decode(from: "49") == "S")
    #expect(try decoder.decode(from: "50") == "Y")
    #expect(try decoder.decode(from: "51") == "ナ")
    #expect(try decoder.decode(from: "52") == "ニ")
    #expect(try decoder.decode(from: "53") == "ヌ")
    #expect(try decoder.decode(from: "54") == "ネ")
    #expect(try decoder.decode(from: "55") == "ノ")
    #expect(try decoder.decode(from: "56") == "U")
    #expect(try decoder.decode(from: "57") == "V")
    #expect(try decoder.decode(from: "58") == "W")
    #expect(try decoder.decode(from: "59") == "X")
    #expect(try decoder.decode(from: "60") == "/")
    #expect(try decoder.decode(from: "61") == "ハ")
    #expect(try decoder.decode(from: "62") == "ヒ")
    #expect(try decoder.decode(from: "63") == "フ")
    #expect(try decoder.decode(from: "64") == "ヘ")
    #expect(try decoder.decode(from: "65") == "ホ")
    #expect(try decoder.decode(from: "66") == "Z")
    #expect(try decoder.decode(from: "67") == "?")
    #expect(try decoder.decode(from: "68") == "!")
    #expect(try decoder.decode(from: "69") == "-")
    #expect(try decoder.decode(from: "70") == "●")
    #expect(try decoder.decode(from: "71") == "マ")
    #expect(try decoder.decode(from: "72") == "ミ")
    #expect(try decoder.decode(from: "73") == "ム")
    #expect(try decoder.decode(from: "74") == "メ")
    #expect(try decoder.decode(from: "75") == "モ")
    #expect(try decoder.decode(from: "76") == "¥")
    #expect(try decoder.decode(from: "77") == "&")
    #expect(try decoder.decode(from: "78") == "●")
    #expect(try decoder.decode(from: "79") == "●")
    #expect(try decoder.decode(from: "80") == "●")
    #expect(try decoder.decode(from: "81") == "ヤ")
    #expect(try decoder.decode(from: "82") == "（")
    #expect(try decoder.decode(from: "83") == "ユ")
    #expect(try decoder.decode(from: "84") == "）")
    #expect(try decoder.decode(from: "85") == "ヨ")
    #expect(try decoder.decode(from: "86") == "*")
    #expect(try decoder.decode(from: "87") == "#")
    #expect(try decoder.decode(from: "88") == " ")
    #expect(try decoder.decode(from: "89") == "●")
    #expect(try decoder.decode(from: "90") == "5")
    #expect(try decoder.decode(from: "91") == "ラ")
    #expect(try decoder.decode(from: "92") == "リ")
    #expect(try decoder.decode(from: "93") == "ル")
    #expect(try decoder.decode(from: "94") == "レ")
    #expect(try decoder.decode(from: "95") == "ロ")
    #expect(try decoder.decode(from: "96") == "1")
    #expect(try decoder.decode(from: "97") == "2")
    #expect(try decoder.decode(from: "98") == "3")
    #expect(try decoder.decode(from: "99") == "4")
  }  
}
