import TwoTouchParser
import Testing

actor TwoTouchDecoderTests {
  @Test
  func decode_1112324493() throws {
    let decoder = TwoTouchDecoder()
    let result = try! decoder.decode(from: "1112324493")
    #expect(result == "あいしてる")
  }
  
  @Test
  func decode() throws {
    let decoder = TwoTouchDecoder()
    #expect(try decoder.decode(from: "00") == "0")
    #expect(try decoder.decode(from: "01") == "わ")
    #expect(try decoder.decode(from: "02") == "を")
    #expect(try decoder.decode(from: "03") == "ん")
    #expect(try decoder.decode(from: "04") == "゛")
    #expect(try decoder.decode(from: "05") == "。")
    #expect(try decoder.decode(from: "06") == "6")
    #expect(try decoder.decode(from: "07") == "7")
    #expect(try decoder.decode(from: "08") == "8")
    #expect(try decoder.decode(from: "09") == "9")
    #expect(try decoder.decode(from: "10") == "E")
    #expect(try decoder.decode(from: "11") == "あ")
    #expect(try decoder.decode(from: "12") == "い")
    #expect(try decoder.decode(from: "13") == "う")
    #expect(try decoder.decode(from: "14") == "え")
    #expect(try decoder.decode(from: "15") == "お")
    #expect(try decoder.decode(from: "16") == "A")
    #expect(try decoder.decode(from: "17") == "B")
    #expect(try decoder.decode(from: "18") == "C")
    #expect(try decoder.decode(from: "19") == "D")
    #expect(try decoder.decode(from: "20") == "J")
    #expect(try decoder.decode(from: "21") == "か")
    #expect(try decoder.decode(from: "22") == "き")
    #expect(try decoder.decode(from: "23") == "く")
    #expect(try decoder.decode(from: "24") == "け")
    #expect(try decoder.decode(from: "25") == "こ")
    #expect(try decoder.decode(from: "26") == "F")
    #expect(try decoder.decode(from: "27") == "G")
    #expect(try decoder.decode(from: "28") == "H")
    #expect(try decoder.decode(from: "29") == "I")
    #expect(try decoder.decode(from: "30") == "O")
    #expect(try decoder.decode(from: "31") == "さ")
    #expect(try decoder.decode(from: "32") == "し")
    #expect(try decoder.decode(from: "33") == "す")
    #expect(try decoder.decode(from: "34") == "せ")
    #expect(try decoder.decode(from: "35") == "そ")
    #expect(try decoder.decode(from: "36") == "K")
    #expect(try decoder.decode(from: "37") == "L")
    #expect(try decoder.decode(from: "38") == "M")
    #expect(try decoder.decode(from: "39") == "N")
    #expect(try decoder.decode(from: "40") == "T")
    #expect(try decoder.decode(from: "41") == "た")
    #expect(try decoder.decode(from: "42") == "ち")
    #expect(try decoder.decode(from: "43") == "つ")
    #expect(try decoder.decode(from: "44") == "て")
    #expect(try decoder.decode(from: "45") == "と")
    #expect(try decoder.decode(from: "46") == "P")
    #expect(try decoder.decode(from: "47") == "Q")
    #expect(try decoder.decode(from: "48") == "R")
    #expect(try decoder.decode(from: "49") == "S")
    #expect(try decoder.decode(from: "50") == "Y")
    #expect(try decoder.decode(from: "51") == "な")
    #expect(try decoder.decode(from: "52") == "に")
    #expect(try decoder.decode(from: "53") == "ぬ")
    #expect(try decoder.decode(from: "54") == "ね")
    #expect(try decoder.decode(from: "55") == "の")
    #expect(try decoder.decode(from: "56") == "U")
    #expect(try decoder.decode(from: "57") == "V")
    #expect(try decoder.decode(from: "58") == "W")
    #expect(try decoder.decode(from: "59") == "X")
    #expect(try decoder.decode(from: "60") == "/")
    #expect(try decoder.decode(from: "61") == "は")
    #expect(try decoder.decode(from: "62") == "ひ")
    #expect(try decoder.decode(from: "63") == "ふ")
    #expect(try decoder.decode(from: "64") == "へ")
    #expect(try decoder.decode(from: "65") == "ほ")
    #expect(try decoder.decode(from: "66") == "Z")
    #expect(try decoder.decode(from: "67") == "?")
    #expect(try decoder.decode(from: "68") == "!")
    #expect(try decoder.decode(from: "69") == "-")
    #expect(try decoder.decode(from: "70") == "●")
    #expect(try decoder.decode(from: "71") == "ま")
    #expect(try decoder.decode(from: "72") == "み")
    #expect(try decoder.decode(from: "73") == "む")
    #expect(try decoder.decode(from: "74") == "め")
    #expect(try decoder.decode(from: "75") == "も")
    #expect(try decoder.decode(from: "76") == "¥")
    #expect(try decoder.decode(from: "77") == "&")
    #expect(try decoder.decode(from: "78") == "●")
    #expect(try decoder.decode(from: "79") == "●")
    #expect(try decoder.decode(from: "80") == "●")
    #expect(try decoder.decode(from: "81") == "や")
    #expect(try decoder.decode(from: "82") == "（")
    #expect(try decoder.decode(from: "83") == "ゆ")
    #expect(try decoder.decode(from: "84") == "）")
    #expect(try decoder.decode(from: "85") == "よ")
    #expect(try decoder.decode(from: "86") == "*")
    #expect(try decoder.decode(from: "87") == "#")
    #expect(try decoder.decode(from: "88") == " ")
    #expect(try decoder.decode(from: "89") == "●")
    #expect(try decoder.decode(from: "90") == "5")
    #expect(try decoder.decode(from: "91") == "ら")
    #expect(try decoder.decode(from: "92") == "り")
    #expect(try decoder.decode(from: "93") == "る")
    #expect(try decoder.decode(from: "94") == "れ")
    #expect(try decoder.decode(from: "95") == "ろ")
    #expect(try decoder.decode(from: "96") == "1")
    #expect(try decoder.decode(from: "97") == "2")
    #expect(try decoder.decode(from: "98") == "3")
    #expect(try decoder.decode(from: "99") == "4")
  }
  
}
